### ISSUE TITLE
README.md link to schema code generator broken

### ISSUE THREAD

**Issue by slawr** [COVESA/graphql-vss-data-server#1]
The link to https://github.com/COVESA/graphql_schema2cpp_codegen in the README.md is broken. Unclear where it should be pointing so raised this issue rather than send a fix

**Comment by alexanderdomin** [comment]
You are right. Profusion and I are working on a release. I hope this repo will be available end of this or beginning on next week.

**Comment by alexanderdomin** [comment]
Working now :-)

**Comment by alexanderdomin** [comment]
Done

**Comment by slawr** [comment]
Confirm fixed
