### ISSUE TITLE
question: what is the top level component or documentation page?

### ISSUE THREAD

**Issue by slawr** [COVESA/graphql-vss-data-server#3]
If we were trying to refer someone to this collection of GraphQL components what is the top level component and documentation we would link to for that person to understand the scope of the project and its sub-components? Is it this one and its root README.md?

**Comment by g7fernandes** [comment]
Currently, the documentation is on the README.md.

**Comment by slawr** [comment]
> Currently, the documentation is on the README.md.

Hi, understood. I think there is a good set of markdown documentation btw. Maybe I am misunderstanding your reply, but let me try and ask the question in a different way.

If you had to link to one README.md in this group of GraphQL components to give the best introduction to the project which one would it be? https://github.com/COVESA/graphql-vss-data-server/blob/master/README.md?

**Comment by slawr** [comment]
Issue has been open a while. I choose to link to https://github.com/COVESA/graphql-vss-data-server as it seems a reasonable "top level" component. Closing issue.
